name: Deploy Json

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: CURL
        run: |
            mkdir api && touch list.json
            curl --request GET \
            --url https://unogsng.p.rapidapi.com/expiring?countrylist=348 \
            --header 'x-rapidapi-host: unogsng.p.rapidapi.com' \
            --header 'x-rapidapi-key: ${{ secrets.RAPID_API_KEY }}' >> api/list.json

      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: none@none.none
          branch: gh-pages
          build_dir: api
          jekyll: no
